apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
  name: vault-config-ha
  namespace: hashicorp
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "[::]:8201"
      tls_disable    = 1
    }
    raw_storage_endpoint     = true
    disable_sealwrap     = false
    disable_printable_check = true
    api_addr         = "http://POD_IP:8200"
    storage "consul" {
      path = "vault"
      service = "vault"
      address = "consul-consul-server.default.svc:8500"
     }
